// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtY5v_Ao8KxRNh9T3-uvWGusVMDnMi_fs',
    appId: '1:836566003503:web:b152f8d89a4a44453bfbda',
    messagingSenderId: '836566003503',
    projectId: 'lunavapp',
    authDomain: 'lunavapp.firebaseapp.com',
    storageBucket: 'lunavapp.firebasestorage.app',
    measurementId: 'G-54C4KJZFWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX5tCxz038GerA1A1jPsG2Zbr92qtQtbg',
    appId: '1:836566003503:android:5146df16cb44b88c3bfbda',
    messagingSenderId: '836566003503',
    projectId: 'lunavapp',
    storageBucket: 'lunavapp.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtY5v_Ao8KxRNh9T3-uvWGusVMDnMi_fs',
    appId: '1:836566003503:web:f9b0683b31dc00e93bfbda',
    messagingSenderId: '836566003503',
    projectId: 'lunavapp',
    authDomain: 'lunavapp.firebaseapp.com',
    storageBucket: 'lunavapp.firebasestorage.app',
    measurementId: 'G-2J3PETX49B',
  );
}
